# Build the C# project

name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build --configuration Release EDMXTrimmer
    - name: Publish
      run: dotnet publish --configuration Release EDMXTrimmer --output ./publish
    - name: Upload EDMXTrimmer
      uses: actions/upload-artifact@v2
      with:
        name: EDMXTrimmer
        path: ./publish
    - name: Create package
      run: dotnet pack --configuration Release EDMXTrimmer --output ./publish
    - name: Publish the package to GPR
      run: dotnet nuget push ./publish/*.nupkg